### ISSUE TITLE
`<` of closing style tag gets 'source.css' scope

### ISSUE THREAD

**Issue by aeschli** [textmate/html.tmbundle#74] opened 2017-08-31 11:05 UTC
```html
<html>
<head>
	<style>
	</style>
</head>
```

The `<` of `</style>` tag gets 'source.css' scope. That leads to wrong colorizations when a theme colorizes 'scope.css'

![image](https://user-images.githubusercontent.com/6461412/29920225-d3eeef48-8e4c-11e7-8f42-994bac6e4a9c.png)

**Comment by infininight** [comment] 2017-09-04 05:59
Duplicate of #65, the coloring issue is specific to the theme used and would depend on how the scope ranking is done.

**Closed by infininight** 2017-09-04 05:59 UTC
