### ISSUE TITLE
script type="module" doesn't highlights as javascript

### ISSUE THREAD

**Issue by aeschli** [textmate/html.tmbundle#61] opened 2017-05-03 08:58 UTC
_From @NicolasParada on May 2, 2017 7:27_

- VSCode Version: 1.12.0-insider
- OS Version: Windows 10 15063.250

```js
<script type="module"></script>
```
Scripts of type "module" on `.html` files are not getting correctly highlighted. They just shows as plain text I guess...

_Copied from original issue: Microsoft/vscode#25760_

**Comment by infininight** [comment] 2017-05-04 07:40
Duplicate of #59.

**Closed by infininight** 2017-05-04 07:40 UTC
