### ISSUE TITLE
Double hyphens in comments being flagged as red, comments not closing

### ISSUE THREAD

**Issue by aeschli** [textmate/html.tmbundle#58] opened 2017-04-19 13:43 UTC
_From @crops11 on April 13, 2017 13:50_

- VSCode Version: 1.11.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Enter comment tags like so 
2. Double hyphen in the closing tag is highlighted in red, comment tag doesn't close

_Copied from original issue: Microsoft/vscode#24685_

**Comment by infininight** [comment] 2017-04-19 21:41
This is a duplicate of #45. This is also being discussed in #49.

Basically this until extremely recently in the WhatWG version of HTML5 was illegal, it still is in HTML 4 and the W3C version of HTML5. To maximize compatibility we will likely be keeping the stricter interpretation for now.

**Closed by infininight** 2017-04-19 21:41 UTC
